/**
 * Changelog data for What's New dialog
 * This file is auto-generated by scripts/generate-changelog.js at build time
 * DO NOT EDIT MANUALLY
 */

export interface ChangelogData {
  features: string[];
  improvements: string[];
  bugFixes: string[];
}

export const changelog: ChangelogData = {
  "features": [
    "Support multiple GitHub email addresses for domain validation (#26)"
  ],
  "improvements": [],
  "bugFixes": []
};

export default changelog;
