/**
 * Changelog data for What's New dialog
 * This file is auto-generated by scripts/generate-changelog.js at build time
 * DO NOT EDIT MANUALLY
 */

export interface ChangelogData {
  features: string[];
  improvements: string[];
  bugFixes: string[];
}

export const changelog: ChangelogData = {
  "features": [],
  "improvements": [],
  "bugFixes": [
    "Admin view: Correct API token expiry display and add clickable filter cards (#9)"
  ]
};

export default changelog;
